project:
  type: website

website:
  title: "2023_DAIE_ICA_2_FM"
  navbar:
    left:
      - href: index.qmd
        text: Index
      - href: DataView.qmd
        text: Data View

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual